"use client";

import { ChangeEvent, PointerEvent, useEffect, useRef, useState } from 'react';

type P={x:number;y:number};
type Style={id:string;title:string;description:string;imageUrl:string;prompt:string;sourceUrl?:string};
type Finish={name:string;colors:string[];prompt:string};

declare global{interface Window{SpeechRecognition?:any;webkitSpeechRecognition?:any;webkitAudioContext?:typeof AudioContext}}

const svg=(a:string,b:string,c:string)=>`data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='640' height='360'%3E%3Crect width='640' height='360' fill='${a}'/%3E%3Cpath d='M-40 250 C120 80 280 360 700 90' stroke='${b}' stroke-width='36' fill='none' opacity='.72'/%3E%3Cpath d='M-60 310 C160 120 320 390 720 160' stroke='${c}' stroke-width='13' fill='none' opacity='.55'/%3E%3Cpath d='M0 180 C180 20 340 270 680 40' stroke='%23ffffff' stroke-width='42' fill='none' opacity='.9'/%3E%3C/svg%3E`;
const fallback:Style[]=[
{id:'gallery',title:'Option 1: Gallery White Swirl',description:'Clean white metallic epoxy with soft silver ribbon movement.',imageUrl:svg('%23fbfbf8','%23d9dde2','%23bfc6cc'),prompt:'clean white metallic epoxy with soft silver ribbon swirls'},
{id:'pearl',title:'Option 2: Pearl Cloud',description:'Cloudlike white pearl epoxy with faint warm veining.',imageUrl:svg('%23fffdfa','%23eee7dc','%23d3d1ca'),prompt:'pearl white metallic epoxy with cloudlike movement'},
{id:'ice',title:'Option 3: Ice Marble',description:'White epoxy with crisp gray marble-like movement.',imageUrl:svg('%23f8f9f9','%23cfd6da','%239da8ae'),prompt:'white ice-marble metallic epoxy with gray swirl veins'}
];
const baseFinish:Finish={name:'White Swirl Epoxy',colors:['#fff','#d9dde2','#f4f2ec'],prompt:'Replace only the masked floor with a glossy white swirl metallic epoxy floor, preserving room perspective, shadows, walls, furniture, and baseboards.'};

export default function Home(){
const canvasRef=useRef<HTMLCanvasElement|null>(null);const [img,setImg]=useState<HTMLImageElement|null>(null);const [data,setData]=useState('');const [bounds,setBounds]=useState({x:0,y:0,width:0,height:0});const [poly,setPoly]=useState<P[]>([]);const [styles,setStyles]=useState<Style[]>(fallback);const [chosen,setChosen]=useState<Style>(fallback[0]);const [finish,setFinish]=useState<Finish>(baseFinish);const [cmd,setCmd]=useState('Hey Vizzy, outline my floor, search for white swirl epoxy floors, show me three options, and use option 1.');const [status,setStatus]=useState('Vizzy is ready');const [readout,setReadout]=useState('Upload a photo, then ask Vizzy what floor style you want.');const [busy,setBusy]=useState(false);const [listening,setListening]=useState(false);const [elapsed,setElapsed]=useState(0);
useEffect(()=>{let t:any;if(busy){setElapsed(0);t=setInterval(()=>setElapsed(v=>v+1),1000)}return()=>clearInterval(t)},[busy]);useEffect(()=>draw(),[img,poly,chosen,finish]);
function fit(i:HTMLImageElement){const c=canvasRef.current;if(!c)return{x:0,y:0,width:0,height:0};const r=Math.min(c.width/i.width,c.height/i.height),w=i.width*r,h=i.height*r;return{x:(c.width-w)/2,y:(c.height-h)/2,width:w,height:h}}
function mask(c:HTMLCanvasElement){const m=document.createElement('canvas');m.width=c.width;m.height=c.height;const x=m.getContext('2d');if(!x||poly.length<3)return m;x.beginPath();x.moveTo(poly[0].x,poly[0].y);poly.slice(1).forEach(p=>x.lineTo(p.x,p.y));x.closePath();x.fillStyle='#fff';x.fill();return m}
function drawStyle(x:CanvasRenderingContext2D,c:HTMLCanvasElement){const g=x.createLinearGradient(0,c.height,c.width,0);g.addColorStop(0,finish.colors[0]);g.addColorStop(.55,finish.colors[1]);g.addColorStop(1,finish.colors[2]);x.fillStyle=g;x.fillRect(0,0,c.width,c.height);for(let i=0;i<30;i++){x.beginPath();const y=c.height/30*i+Math.sin(i)*28;x.moveTo(0,y);for(let q=0;q<=c.width;q+=80)x.lineTo(q,y+Math.sin(q/120+i)*46);x.strokeStyle=i%2?'rgba(255,255,255,.38)':'rgba(160,168,174,.24)';x.lineWidth=i%3?14:26;x.stroke()}}
function draw(){const c=canvasRef.current,x=c?.getContext('2d');if(!c||!x)return;x.clearRect(0,0,c.width,c.height);x.fillStyle='rgba(255,255,255,.35)';x.fillRect(0,0,c.width,c.height);if(!img)return;const b=fit(img);setBounds(b);x.drawImage(img,b.x,b.y,b.width,b.height);if(poly.length>2){const p=document.createElement('canvas');p.width=c.width;p.height=c.height;const px=p.getContext('2d');if(px){drawStyle(px,p);px.globalCompositeOperation='destination-in';px.drawImage(mask(c),0,0);x.globalAlpha=.82;x.drawImage(p,0,0);x.globalAlpha=1}x.strokeStyle='rgba(84,199,187,.95)';x.fillStyle='#fff';x.lineWidth=3;x.beginPath();x.moveTo(poly[0].x,poly[0].y);poly.slice(1).forEach(v=>x.lineTo(v.x,v.y));x.closePath();x.stroke();poly.forEach(v=>{x.beginPath();x.arc(v.x,v.y,7,0,Math.PI*2);x.fill();x.stroke()})}}
function upload(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{const i=new Image();i.onload=()=>{setImg(i);setData(String(r.result));setPoly([]);setStatus('Photo loaded');setReadout('Tell Vizzy what you want, or click Do it all.')};i.src=String(r.result)};r.readAsDataURL(f)}
function point(e:PointerEvent<HTMLCanvasElement>){const c=canvasRef.current!,r=c.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*c.width,y:(e.clientY-r.top)/r.height*c.height}}
async function detect(){if(!data){setStatus('Upload a photo first');return false}setBusy(true);setStatus('Vizzy is outlining your floor');try{const r=await fetch('/api/detect-floor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({imageDataUrl:data})});const j=await r.json();if(!Array.isArray(j.polygon))throw new Error(j.error||'Could not outline floor');const b=img?fit(img):bounds;setPoly(j.polygon.map((p:P)=>({x:b.x+p.x*b.width,y:b.y+p.y*b.height})));setReadout(`${j.mode==='ai'?'AI detected':'Estimated'} floor. Confidence ${Math.round((j.confidence||0)*100)}%. ${j.notes||''}`);setStatus('Floor outlined');setBusy(false);return true}catch(e:any){setStatus(e.message||'Outline failed');setReadout('You can still tap the photo to outline the floor manually.');setBusy(false);return false}}
async function search(){setBusy(true);setStatus('Vizzy is searching for style ideas');try{const r=await fetch('/api/style-search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({command:cmd})});const j=await r.json();const o=j.options?.length?j.options:fallback;setStyles(o);choose(o[0],0);setStatus('Three style options ready');setReadout('Choose a card or say which option you like.');setBusy(false);return o as Style[]}catch{setStyles(fallback);setBusy(false);return fallback}}
function choose(s:Style,i:number){setChosen(s);setFinish({...baseFinish,name:s.title.replace(/^Option \d+:\s*/u,''),prompt:`${baseFinish.prompt} Match option ${i+1}: ${s.prompt}`});setStatus(`Option ${i+1} selected`)}
function selectedIndex(){return Math.max(0,Number(cmd.toLowerCase().match(/option\s*(1|2|3)/u)?.[1]||1)-1)}
async function renderAi(){const c=canvasRef.current;if(!c||!img||poly.length<3){setStatus('Upload a photo and outline the floor first');return}setBusy(true);setStatus('Vizzy is changing your floor');const s=document.createElement('canvas');s.width=c.width;s.height=c.height;const x=s.getContext('2d')!;x.fillStyle='#fff';x.fillRect(0,0,s.width,s.height);x.drawImage(img,bounds.x,bounds.y,bounds.width,bounds.height);try{const r=await fetch('/api/render-floor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({imageDataUrl:s.toDataURL('image/png'),maskDataUrl:mask(c).toDataURL('image/png'),finish,style:chosen})});const j=await r.json();if(!r.ok||!j.image)throw new Error(j.error||'Render failed');const ni=new Image();ni.onload=()=>{setImg(ni);setData(j.image);setPoly([]);chime();setStatus('Bam. Your floor preview is ready.');setReadout('This is an AI visualization, not a final installation guarantee.')};ni.src=j.image}catch(e:any){setStatus(e.message||'Render failed');setReadout('Add OpenAI environment variables in Vercel for final AI rendering.')};setBusy(false)}
async function run(){if(!data){setStatus('Upload a photo first');return}const o=await search();choose(o[selectedIndex()]||o[0],selectedIndex());const ok=poly.length>2||await detect();if(ok)await renderAi()}
function listen(){const S=window.SpeechRecognition||window.webkitSpeechRecognition;if(!S){setStatus('Voice is not supported here. Use text.');return}const r=new S();r.lang='en-US';r.interimResults=false;r.onstart=()=>{setListening(true);setStatus('Vizzy is listening')};r.onresult=(e:any)=>{setCmd(e.results[0][0].transcript);setStatus('Voice command captured')};r.onend=()=>setListening(false);r.start()}
function chime(){const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const a=new A(),g=a.createGain();g.gain.setValueAtTime(.0001,a.currentTime);g.gain.exponentialRampToValueAtTime(.08,a.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+.45);g.connect(a.destination);[523,659,784].forEach((f,i)=>{const o=a.createOscillator();o.frequency.value=f;o.connect(g);o.start(a.currentTime+i*.08);o.stop(a.currentTime+.38+i*.08)})}
function download(){const c=canvasRef.current;if(!c)return;const a=document.createElement('a');a.download='vizual-x-floor-preview.png';a.href=c.toDataURL('image/png');a.click()}
return <main className="page"><header className="topbar"><div className="brand"><span className="brand-mark"/><span><strong>Vizual-X</strong><small>Vizzy AI floor studio</small></span></div><div className="status">{status}</div></header><section className="hero"><div><p className="eyebrow">Say Hey Vizzy</p><h1>Speak a floor idea. Vizzy finds it, outlines it, and renders it.</h1><p>Upload a room photo, ask for a style like white swirl epoxy floor, choose one of three references, and Vizzy maps the look onto your floor.</p></div><div className="vizzy-card"><div className="vizzy-face"><div className="vizzy-orbit"><div className="vizzy-dot"/></div></div><p>Try: Hey Vizzy, outline my floor, search for white swirl epoxy floors, show me three options, and use option one.</p></div></section><section className="app-grid"><div className="canvas-shell"><canvas ref={canvasRef} width={1280} height={820} onPointerDown={e=>{if(img){setPoly(v=>[...v,point(e)]);setStatus('Manual floor point added')}}}/>{!img&&<div className="empty"><span>Upload a floor photo</span><strong>Vizzy will do the hard part from there.</strong></div>}</div><aside className="side"><section className="panel"><label className="upload"><input type="file" accept="image/png,image/jpeg,image/webp" onChange={upload}/>Upload customer floor photo</label></section><section className="panel command-box"><h2>Tell Vizzy</h2><p>Use voice or text. Vizzy understands outline my floor, search white swirl epoxy, and use option 1.</p><textarea value={cmd} onChange={e=>setCmd(e.target.value)}/><div className="row"><button onClick={listen} disabled={listening}>🎙 {listening?'Listening':'Voice'}</button><button className="magic" onClick={run} disabled={busy}>✨ Do it all</button></div></section><section className="panel"><h2>Style search</h2><p>Vizzy finds three rectangular inspiration choices.</p><button className="primary" onClick={search} disabled={busy}>Find 3 floor styles</button><div className="styles">{styles.map((s,i)=><button key={s.id} className={`style ${chosen.id===s.id?'active':''}`} onClick={()=>choose(s,i)}><span className="thumb"><img src={s.imageUrl} alt={s.title}/></span><span><strong>{s.title}</strong><span>{s.description}</span></span></button>)}</div></section><section className="panel"><h2>Render</h2><p>{readout}</p><div className={`timer ${busy?'':'hidden'}`}><span className="hourglass">⌛</span><span>{elapsed}s elapsed</span></div><div className="row"><button onClick={detect} disabled={busy}>Outline floor</button><button className="primary" onClick={renderAi} disabled={busy}>Render floor</button></div><button onClick={download}>Download preview</button></section></aside></section></main>}
